version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    container_name: deploy-env
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             gunicorn --bind 0.0.0.0:80 OpinionProject.wsgi:application"
    restart: always